import json
import os

def corregir_urls():
    if not os.path.exists("equipos.json"):
        print("❌ No se encontró equipos.json")
        return

    with open("equipos.json", "r", encoding="utf-8") as f:
        db = json.load(f)

    # DICCIONARIO DE MAPEO EXACTO (BE SOCCER)
    # He corregido los que mencionaste y los más propensos a error
    MAPEOS = {
        # Grandes Europa
        "man city": "manchester-city-fc",
        "man united": "manchester-united-fc",
        "arsenal": "arsenal",
        "bayern": "bayern-munich",
        "liverpool": "liverpool",
        "inter": "internazionale",
        "barcelona": "barcelona",
        "paris sg": "paris-saint-germain",
        "aston villa": "aston-villa",
        "chelsea": "chelsea",
        "real madrid": "real-madrid",
        "newcastle": "newcastle-united-fc",
        "brentford": "brentford",
        "sporting": "sporting-cp",
        "dortmund": "borussia-dortmund",
        "bournemouth": "afc-bournemouth",
        "milan": "milan",
        "brighton": "brighton-amp-hove-albion",
        "everton": "everton",
        "benfica": "benfica",
        "juventus": "juventus",
        "leverkusen": "bayer-leverkusen",
        "tottenham": "tottenham-hotspur",
        "atletico": "atletico-madrid",
        "roma": "as-roma",
        "fulham": "fulham",
        "napoli": "napoli",
        "atalanta": "atalanta",
        "crystal palace": "crystal-palace",
        "leeds": "leeds-united",
        "forest": "nottingham-forest",
        "porto": "porto",
        "lyon": "olympique-lyonnais",
        "psv": "psv",
        "lens": "lens",
        "betis": "real-betis",
        "stuttgart": "vfb-stuttgart",
        "west ham": "west-ham-united",
        "rb leipzig": "rb-leipzig",
        "marseille": "olympique-marseille",
        "hoffenheim": "hoffenheim",
        "brugge": "club-brugge",
        "villarreal": "villarreal",
        "como": "como-calcio",
        "st gillis": "union-saint-gilloise",
        "galatasaray": "galatasaray",
        "lazio": "lazio",
        "sunderland": "sunderland",
        "olympiakos": "olympiakos-piraeus",
        "lille": "lille",
        "burnley": "burnley",
        "bilbao": "athletic-bilbao",
        "bologna": "bologna",
        "strasbourg": "strasbourg",
        "fenerbahce": "fenerbahce",
        "bodoe glimt": "bodo-glimt",
        "braga": "sporting-braga",
        "freiburg": "sc-freiburg",
        "midtjylland": "midtjylland",
        "celta": "celta-vigo",
        "monaco": "monaco",
        "frankfurt": "eintracht-frankfurt",
        "wolves": "wolverhampton",
        "rennes": "stade-rennais",
        "sociedad": "real-sociedad",
        "osasuna": "osasuna",
        "zenit": "zenit-st-petersburg",
        "fiorentina": "fiorentina",
        "mainz": "mainz-05",
        "slavia praha": "slavia-praha",
        "brest": "stade-brestois-29",
        "toulouse": "toulouse",
        "valencia": "valencia",
        "fc krasnodar": "fc-krasnodar",
        "ipswich": "ipswich-town",
        "aek": "aek-athens",
        "paok": "paok-thessaloniki",
        "rayo vallecano": "rayo-vallecano",
        "genoa": "genoa",
        "sassuolo": "sassuolo",
        "espanyol": "espanyol",
        "lorient": "lorient",
        "torino": "torino",
        "werder": "werder-bremen",
        "middlesbrough": "middlesbrough",
        "cagliari": "cagliari",
        "getafe": "getafe",
        "union berlin": "union-berlin",
        "mallorca": "mallorca",
        "udinese": "udinese",
        "gladbach": "borussia-monchengladbach",
        "augsburg": "augsburg",
        "wolfsburg": "vfl-wolfsburg",
        "girona": "girona-fc",
        "genk": "racing-genk",
        "coventry": "coventry-city",
        "parma": "parma",
        "feyenoord": "feyenoord",
        "alaves": "alaves",
        "ajax": "ajax",
        "fc kobenhavn": "fc-copenhagen",
        "cska moskva": "cska-moskva",
        "sevilla": "sevilla",
        "venezia": "venezia",
        "hamburg": "hamburger-sv",
        "viking": "viking-fk",
        "viktoria plzen": "viktoria-plzen",
        "nice": "nice",
        "elche": "elche",
        "crvena zvezda": "crvena-zvezda",
        "sparta praha": "sparta-praha",
        "sheffield united": "sheffield-united",
        "lok moskva": "lokomotiv-moskva",
        "millwall": "millwall",
        "le havre": "le-havre",
        "aarhus": "agf-aarhus",
        "celtic": "celtic",
        "paphos": "paphos",
        "levante": "levante",
        "auxerre": "auxerre",
        "koeln": "1-fc-koln",
        "southampton": "southampton",
        "hull": "hull-city",
        "angers": "angers-sco",
        "cremonese": "cremonese",
        "karabakh agdam": "qarabag",
        "panathinaikos": "panathinaikos",
        "lecce": "lecce",
        "gil vicente": "gil-vicente-fc",
        "st pauli": "st-pauli",
        "spartak moskva": "spartak-moskva",
        "brondby": "brondby-if",
        "rangers": "rangers-fc",
        "guimaraes": "vitoria-guimaraes",
        "monza": "monza",
        "derby": "derby-county",
        "reims": "stade-de-reims",
        "st truiden": "sint-truidense-vv",
        "mjaellby": "mjallby-aif",
        "shakhtar": "shakhtar-donetsk",
        "frosinone": "frosinone",
        "famalicao": "fc-famalicao",
        "oviedo": "real-oviedo",
        "castellon": "castellon",
        "norwich": "norwich-city",
        "dinamo zagreb": "dinamo-zagreb",
        "rakow": "rakow-czestochowa",
        "santander": "racing-santander",
        "bristol city": "bristol-city",
        "almeria": "almeria",
        "paris fc": "paris-fc"
    }

    for nombre_key, info in db.items():
        # Buscamos en el mapeo, si no está, aplicamos una limpieza básica
        if nombre_key in MAPEOS:
            slug = MAPEOS[nombre_key]
        else:
            # Limpieza por defecto para los que no estén en la lista
            slug = info['nombre'].lower().replace(" ", "-").replace(".", "")
        
        db[nombre_key]["slug_besoccer"] = slug

    with open("equipos.json", "w", encoding="utf-8") as f:
        json.dump(db, f, indent=4, ensure_ascii=False)

    print(f"✅ Se han procesado {len(db)} equipos con sus slugs de BeSoccer.")

if __name__ == "__main__":
    corregir_urls()